### ISSUE TITLE
Link in tutorial is incorrect

### ISSUE THREAD

**Issue by LanceALaughlin** [Freenove/Freenove_Robot_Dog_Kit_for_Raspberry_Pi#10]
On page 109 of the tutorial pdf, the link to this repository points to https://github.com/Freenove/Freenove_Four_wheeled_Smart_Car_Kit_for_Raspberry_Pi/archive/master.zip

instead of: https://github.com/Freenove/Freenove_Robot_Dog_Kit_for_Raspberry_Pi/archive/master.zip

This causes the following scripts to fail.

**Comment by ZhiJGuo** [comment]
Thank you for your feedback, we will revise the tutorial @LanceALaughlin
