### ISSUE TITLE
Low-level C or C++ libraries

### ISSUE THREAD

**Issue by matsbror** [Freenove/Freenove_Robot_Dog_Kit_for_Raspberry_Pi#22]
In addition to the Python libraries, do you also have C or C++ lirbraries I can use to program the Robot Dog?

**Comment by Shaynee-MO** [comment]
Sorry, we do not have C or C++ libraries for this robot.

**Comment by matsbror** [comment]
Thank you! I did some research and the key seems to be the i2c library. It should not be to difficult to replicate the library in C++. I’ll let you know once I have it.
