### ISSUE TITLE
Can't get LED module to work

### ISSUE THREAD

**Issue by matsbror** [Freenove/Freenove_Robot_Dog_Kit_for_Raspberry_Pi#23]
I have just assembled the robot dog. So far most things work as expected. However, not the LED module.
I have doubts when it comes to the wiring. The tutorial shows that the cable should be installed like this:

![image](https://github.com/Freenove/Freenove_Robot_Dog_Kit_for_Raspberry_Pi/assets/10210145/89af639b-fdbc-4ba5-a861-a3955d515f86)

However, with the way that the connectors are mounted (see image below), the cable must be installed with the wires crossed.

![IMG_3705](https://github.com/Freenove/Freenove_Robot_Dog_Kit_for_Raspberry_Pi/assets/10210145/4a0ccf3e-7197-4876-8c45-583a9eab6252)

So referring to the first image, the blue and yellow cables are reversed. 

Can this be rectified in software?

**Comment by Shaynee-MO** [comment]
Hi!

If the cable is reversed, please correct the cable by exchanging the first and third cables on one side and try again.
![image](https://github.com/Freenove/Freenove_Robot_Dog_Kit_for_Raspberry_Pi/assets/118493923/b7fe43c3-c429-4b6d-b5f2-d557c3a5f018)
![image](https://github.com/Freenove/Freenove_Robot_Dog_Kit_for_Raspberry_Pi/assets/118493923/6555a758-a3fb-4264-985f-6307d8e845c7)

Here is a video for your reference.
https://www.youtube.com/shorts/MJEGnXrQUAw

**Comment by matsbror** [comment]
Thanks! I have the right cable order, but the way that the connector is mounted on the boards, they become reversed when connected. So I guess I need to make the cable reversed then.

**Comment by matsbror** [comment]
I reversed the cable to be crossed and can confirm that the LED module now works. One of the connectors is probably mounted wrongly.
