### ISSUE TITLE
Servo Ports

### ISSUE THREAD

**Issue by elatobi** [Freenove/Freenove_Robot_Dog_Kit_for_Raspberry_Pi#5]
I have problems with the Servo Ports 8-15. The Servos are not working and after measuring the Voltage between VDD and GND. The voltage was 1,6V the Ports 0-7 have a Voltage of 4,5V. Are there any ideas how to fix this problem?
Thx

**Comment by ZhiJGuo** [comment]
@elatobi We have received your email, and there will be staff to solve your problem in time.

**Comment by mobcom** [comment]
I am actually having the same exact issue, would appreciate a resolution posted here.

**Comment by ZhiJGuo** [comment]
@mobcom You can send the details of the problem to us (support@freenove.com) by email, and there will be staff to help you solve the problem.
