### ISSUE TITLE
Has no attributes

### ISSUE THREAD

**Issue by NotITNerd** [Freenove/Freenove_Robot_Dog_Kit_for_Raspberry_Pi#8]
When I run Servo.py an error message pops up: "Adafruit_PCA9685" has no attributes "PCA9685". I tried everything I found nothing works.
![IMG_5980](https://user-images.githubusercontent.com/76887416/103468139-c2a54980-4d1b-11eb-84b4-01a72a123597.jpg)

**Comment by ZhiJGuo** [comment]
@NotITNerd 
![image](https://user-images.githubusercontent.com/49022851/103498791-dddd9980-4e80-11eb-88a0-15db2e6762fe.png)
sudo pip3 install adafruit-pca9685

**Comment by ZhiJGuo** [comment]
@NotITNerd  
Please check if your default Python is python3
![image](https://user-images.githubusercontent.com/49022851/103498800-e9c95b80-4e80-11eb-8a4c-b3f1f8ae13cd.png)

**Comment by ZhiJGuo** [comment]
@NotITNerd 
Please check if your default Python is python3
![image](https://user-images.githubusercontent.com/49022851/103498842-0feefb80-4e81-11eb-96d2-155b107087d2.png)
The module can be installed through "sudo pip3 install adafruit-pca9685"

**Comment by NotITNerd** [comment]
![IMG_5985](https://user-images.githubusercontent.com/76887416/103842262-2355be80-505b-11eb-9125-51a02bb22775.jpg)

It is python3 and adafruit-pca9685 is already installed.

**Comment by DenzelChen** [comment]
Did you turn on the TWO switches? Could you please send me some pictures of the issue to support@freenove.com?

**Comment by NotITNerd** [comment]
When I click the LOAD button with the power on it just shuts off. So I cannot have both buttons on with the power on. I think maybe that the PCB was soldered incorrect.

**Comment by NotITNerd** [comment]
I will charge the battery overnight maybe they are just low.
