### ISSUE TITLE
CV module error 

### ISSUE THREAD

**Issue by Drakelive** [Freenove/Freenove_Robot_Dog_Kit_for_Raspberry_Pi#9]
Compiling on Ubuntu 20.10 and Python Python 3.8.6 I get this error: 

File "/home/drake/Sviluppo/Freenove_Robot_Dog_Kit_for_Raspberry_Pi/Code/Client/Face.py", line 8, in __init__
    self.recognizer.read('Face/face.yml')
cv2.error: OpenCV(4.2.0) ../contrib/modules/face/src/facerec.cpp:61: error: (-2:Unspecified error) File can't be opened for reading! in function 'read'

It only works with absolute paths. This is a big problem!

**Comment by DenzelChen** [comment]
Dear customer,
It may be related to openCv. Please reinstall to try.
And as you can see, in our tutorial, we only recommend use the client in windows, mac or Raspberry Pi OS.
If you have more concerns, please contact support@freenove.com
Sincerely,
Denzel
Freenove
